CREATE TABLE [dbo].[ROOMS]
(
	[Id] INT NOT NULL IDENTITY,
	[Name] VARCHAR(255) NOT NULL,
	[HouseId] INT NOT NULL,

	CONSTRAINT PK_ROOMS PRIMARY KEY ([Id]),
	CONSTRAINT UQ_NAME_HOUSE UNIQUE([Name], [HouseId]),
	CONSTRAINT FK_ROOMS_HOUSE FOREIGN KEY ([HouseId]) REFERENCES HOUSES([Id])
)
