CREATE TABLE [dbo].[TASKS]
(
	[Id] INT NOT NULL IDENTITY,
	[Name] VARCHAR(255) NOT NULL,
	[RepetitionPerWeek] INT NOT NULL DEFAULT 1,
	[RoomId] INT,
	[UserId] INT,

	CONSTRAINT PK_TASKS PRIMARY KEY ([Id]),
	CONSTRAINT FK_TASKS_ROOM FOREIGN KEY ([RoomId]) REFERENCES ROOMS([Id]),
	CONSTRAINT FK_TASKS_USER FOREIGN KEY ([UserId]) REFERENCES USERS([Id])
)
