CREATE TABLE [dbo].[USERS]
(
	[Id] INT NOT NULL IDENTITY,
	[Name] VARCHAR(255) NOT NULL,
	[Email] VARCHAR(255) NOT NULL,
	[Password] VARCHAR(255) NOT NULL,

	CONSTRAINT PK_USERS PRIMARY KEY ([Id]),
	CONSTRAINT UQ_USERS_EMAIL UNIQUE([Email])
)
