CREATE TABLE [dbo].[USERS_HOUSES]
(
	[UserId] INT NOT NULL,
	[HouseId] INT NOT NULL,
	[IsOwner] BIT NOT NULL DEFAULT 0,

	CONSTRAINT PK_USERS_HOUSES PRIMARY KEY ([UserId], [HouseId]),
	CONSTRAINT FK_USERS_HOUSES_USER FOREIGN KEY  ([UserId]) REFERENCES USERS([Id]),
	CONSTRAINT FK_USERS_HOUSES_HOUSE FOREIGN KEY ([HouseId]) REFERENCES HOUSES([Id])
)
