#Build app.
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /src # Create a working directory for our source files.
COPY ./*.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c Release -o /publish

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS runtime
WORKDIR /publish
COPY --from=build-env /publish .
EXPOSE 80
ENTRYPOINT ["dotnet", "API.Quereseres.dll"]